### PR TITLE
Update documentation for opera CLI commands

### PR DESCRIPTION
**Pull request by anzoman**
In this PR we are paving the way towards the better opera
documentation. The documentation improvements here include reshaping
docs for opera CLI commands and adding a missing TOSCA CSAR deployment
example. We added a detailed CLI command descriptions and examples with 
svg images that will make the docs more interesting for reading and easy to 
understand.

Updated files are however just files and you can't see directly how documentation
looks like. So I'm attaching the created HTML files from Sphinx build: [opera-docs.zip](https://github.com/xlab-si/xopera-opera/files/5704029/opera-docs.zip)
(after you download and extract please open `index.html` file in your browser).

### CODE REVIEW

**Comment by anzoman** [comment]
@cankarm as we discussed I've updated the target branch for merging from `master` to [`docs-improvements`](https://github.com/xlab-si/xopera-opera/tree/docs-improvements). With this change we will be able to prepare the new opera documentation in it's best possible form and then merge to `master`. You can also continue working on this current branch or move to a new one. 

As we also talked the CSARs will have to be removed from repository's history before merging to master because it's not the best practice to store zip files in git repo. We can upload the to our Template Library solution or keep them here as extracted archives. 

And because this PR also included some important fixes for opera README that need to be merged to master ASAP I've move those three commits to new branch and created a separate PR here: #157 (please take look when you find the time).

**Comment by cankarm** [comment]
I'm sorry to neglect this, as I did not pay enough attention to the GH notifications. I thought that you will not touch documentation for a while, or at least not before doing a sync with me. 

I already created a branch yesterday, `main-docs`,  where I merged all SaaS documentation and your improvements. From this state I started to create massive changes on the documentation basic structure. Things are not pushed yet, as I was still not satisfied with the result - the problem is that if I push now, then further contributions could be also added on the wrong place. I imagine that this branch will be the one where we will jointly push all documentation changes and then they will be merged to the master at the end.

I expect that tomorrow I can prepare something that will be structurally OK, but still there will be much issues that we will need to discuss.

**Comment by anzoman** [comment]
@cankarm ok, no problem, we can then keep thisn PR open and when the time is right and when the docs will be fully prepared we can update this branch and merge.

**Comment by anzoman** [comment]
@cankarm as the new documentation with updated opera CLI commands was already merged I believe that we can close this PR.

**Pull request closed without merging**
